language: node_js
node_js:
  - 8
  - 10
  - 12
  - node

matrix:
  include:
    - name: Lint
      node_js: 12
      script: npm run lint

script: npm run test:ci
after_success: '<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js'
